### ISSUE TITLE
declareMajors

### ISSUE THREAD

**Issue by truevchow** [AY1920S2-CS2103T-W13-4/main#2]
As a user I can declare what my major(s)/minor(s) is/are, so that I get the right graduation requirements to follow.

**Comment by DANamic** [comment]
Implemented in 2c45d815f807fc288ced21d9d898794fd0ca23d5

**Comment by DANamic** [comment]
Also referenced and implemented in aa4a8798766e6df74a2b1c6c1c6a219ab9c53fa0
