### ISSUE TITLE
viewGpaProjection

### ISSUE THREAD

**Issue by truevchow** [AY1920S2-CS2103T-W13-4/main#24]
As a user I can view changes in Grade Point Average (GPA) according to projected grades, so that I can have a better understanding of my academic performance.

**Comment by DANamic** [comment]
Implemented in with identified base structures in 066fc06081ecda9bc38f9860ac26126156402d60, 7d5f59993f51dfc586d919180ceeecb97af54e02 and 5783c1ab74f894ebcb3f9bf3924b37789033b311
