### ISSUE TITLE
declareTracks

### ISSUE THREAD

**Issue by truevchow** [AY1920S2-CS2103T-W13-4/main#6]
As a user I can declare what tracks/specializations (Focus Areas) I am interested/am taking, so that I am given recommendations that will fulfill the requirements of that track/specialization.

**Comment by DANamic** [comment]
@Capeguy @thetruevincentchow We may combine #7 together, since we're focusing on the Computer Science Major, which has Tracks, as opposed to Specialisations (for the flattening of our scope).

**Comment by DANamic** [comment]
Closing this, and merging it as part of #7.
