### ISSUE TITLE
declareSpecialisations

### ISSUE THREAD

**Issue by truevchow** [AY1920S2-CS2103T-W13-4/main#7]
As a user I can declare what tracks/specializations (Focus Areas) I am interested/am taking, so that I am given recommendations that will fulfill the requirements of that track/specialization.

**Comment by DANamic** [comment]
Implemented in dfe2c6d0b6dfe111974c042be0f80671d1e616e0 and further partial implementation in 634eb17ceade1209666d1818f53cb40d950f2ac7
