### ISSUE TITLE
DG Feedback from F11-4

### ISSUE THREAD

**Issue by shanecsj** [AY1920S2-CS2103T-W13-4/main#84]
- In **3.1 Declaration Implementation**, some of the implementations are similar and seem repetitive (e.g. _3.1.1. Declare Major_ and _3.1.2. Declare Minor_) --> maybe such similarities can be summarised into one type?
- In **Appendix B: User Stories**: 
~ All the entries in `As a...` are 'users' --> should be more specific (e.g. Freshman, Sophomore, Final Year, Post-grad)
~ Would be better to sort the user stories by highest to lowest priority so that it's easier to read and understand.

_All these are just suggestions from our group, we are not enforcing anything to be changed (:_

**Comment by Capeguy** [comment]
Thank you @shanecsj for your group's suggestions! I'll address them below:
- For the *3.1 Declaration Implementation* suggestion, we will not resolve this, as the Developer Guide should be thorough in explaining the codebase. As Declare Major and Declare Minor are handled by different command and logic files, their implementations are different and should be verbose.
- For the *Appendix B: User Stories* suggestion, I have gone ahead and sorted them from highest to lowest priority (descending order), and have also made the specific user more focused.

Thank you!
